# nu = 0.00001(x1)
files = [
    #'../proceed_data/proceed_data_v_given/processed_data_u/0_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_given/processed_data_u/0.2_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/0.4_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/1_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/5_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/10_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/15_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/20_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/25_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/30_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/35_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/40_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/45_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/50_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/70_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/90_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/110_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/130_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_u/150_ux_uy_data.txt',
    
]

files_vor = [
    '../proceed_data/proceed_data_v_given/processed_data_vor/0.2_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/5_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/10_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/15_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/20_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/25_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/35_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/40_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/45_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/50_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/70_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/90_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/110_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/130_vor_data.txt',
    '../proceed_data/proceed_data_v_given/processed_data_vor/150_vor_data.txt',
    
]

# nu = 0.0001(x10)
files2 = [
    #'../proceed_data/proceed_data_v_10/processed_data_u/0_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_10/processed_data_u/0.2_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/0.4_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_10/processed_data_u/0.6_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/1_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_10/processed_data_u/2_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_10/processed_data_u/3_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_10/processed_data_u/4_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/5_ux_uy_data.txt',
    #'../proceed_data/proceed_data_v_10/processed_data_u/6_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/10_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/15_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/20_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/25_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/30_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/35_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/40_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/45_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_u/50_ux_uy_data.txt',
]

files2_vor = [
    '../proceed_data/proceed_data_v_10/processed_data_vor/0.2_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/5_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/15_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/20_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/25_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/35_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/40_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/45_vor_data.txt',
    '../proceed_data/proceed_data_v_10/processed_data_vor/50_vor_data.txt',
]

# nu = 0.000005(x0.5)
files3 = [
    # '../../Dropbox/datafile/2x_data/0.4_ux_uy_data.txt',
    # '../../Dropbox/datafile/2x_data/1_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/5_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/15_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/10_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/20_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/25_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/30_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/35_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/40_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/45_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/50_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/70_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/90_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/110_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/130_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/150_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/170_ux_uy_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_u/186_ux_uy_data.txt',
]

files3_vor = [
    '../proceed_data/proceed_data_v_half/processed_data_vor/0.2_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/5_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/10_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/15_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/20_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/25_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/35_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/40_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/45_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/50_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/70_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/90_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/110_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/130_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/150_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/170_vor_data.txt',
    '../proceed_data/proceed_data_v_half/processed_data_vor/186_vor_data.txt',
]

# nu = 0.00002(x2)
files4 = [
    #'../2x/u/0_ux_uy_data.txt',
    # '../../Dropbox/datafile/2x_data/0.4_ux_uy_data.txt',
    # '../../Dropbox/datafile/2x_data/1_ux_uy_data.txt',
    '../2x/u/5_ux_uy_data.txt',
    '../2x/u/10_ux_uy_data.txt',
    '../2x/u/15_ux_uy_data.txt',
    '../2x/u/20_ux_uy_data.txt',
    '../2x/u/25_ux_uy_data.txt',
    '../2x/u/30_ux_uy_data.txt',
    '../2x/u/35_ux_uy_data.txt',
    '../2x/u/40_ux_uy_data.txt',
    '../2x/u/45_ux_uy_data.txt',
    '../2x/u/50_ux_uy_data.txt',
    '../2x/u/70_ux_uy_data.txt',
    '../2x/u/90_ux_uy_data.txt',
    '../2x/u/110_ux_uy_data.txt',
    '../2x/u/130_ux_uy_data.txt',
    '../2x/u/150_ux_uy_data.txt',
]

files4_vor = [
    '../2x/vor/0.2_vor_data.txt',
    '../2x/vor/5_vor_data.txt',
    '../2x/vor/10_vor_data.txt',
    '../2x/vor/15_vor_data.txt',
    '../2x/vor/20_vor_data.txt',
    '../2x/vor/25_vor_data.txt',
    '../2x/vor/30_vor_data.txt',
    '../2x/vor/35_vor_data.txt',
    '../2x/vor/40_vor_data.txt',
    '../2x/vor/45_vor_data.txt',
    '../2x/vor/50_vor_data.txt',
    '../2x/vor/70_vor_data.txt',
    '../2x/vor/90_vor_data.txt',
    '../2x/vor/110_vor_data.txt',
    '../2x/vor/130_vor_data.txt',
    '../2x/vor/150_vor_data.txt',
    
]